---
# This file is managed via modulesync
# https://github.com/voxpupuli/modulesync
# https://github.com/voxpupuli/modulesync_config
HOSTS:
  centos-5-x64:
    default_apply_opts:
      order: random
      strict_variables:
    platform: el-5-x86_64
    hypervisor : docker
    image: tianon/centos:5.10
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'yum install -y crontabs tar wget which'
      - 'sed -i -e "/mingetty/d" /etc/inittab'
CONFIG:
  type: aio
  log_level: debug
...
# vim: syntax=yaml
