---
# This file is managed via modulesync
# https://github.com/voxpupuli/modulesync
# https://github.com/voxpupuli/modulesync_config
HOSTS:
  centos-6-x64:
    default_apply_opts:
      order: random
      strict_variables:
    platform: el-6-x86_64
    hypervisor : docker
    image: centos:6
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'rm -rf /var/run/network/*'
      - 'yum install -y crontabs tar wget'
      - 'rm /etc/init/tty.conf'
CONFIG:
  type: aio
  log_level: debug
...
# vim: syntax=yaml
