---
# This file is managed via modulesync
# https://github.com/voxpupuli/modulesync
# https://github.com/voxpupuli/modulesync_config
HOSTS:
  debian-7-x64:
    default_apply_opts:
      order: random
      strict_variables:
    platform: debian-7-amd64
    hypervisor : docker
    image: debian:7
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'apt-get install -y cron locales-all net-tools wget'
CONFIG:
  type: aio
  log_level: debug
...
# vim: syntax=yaml
