---
# This file is managed via modulesync
# https://github.com/voxpupuli/modulesync
# https://github.com/voxpupuli/modulesync_config
HOSTS:
  ubuntu-1404-x64:
    default_apply_opts:
      order: random
      strict_variables:
    platform: ubuntu-14.04-amd64
    hypervisor : docker
    image: ubuntu:14.04
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - 'rm /usr/sbin/policy-rc.d'
      - 'rm /sbin/initctl; dpkg-divert --rename --remove /sbin/initctl'
      - 'apt-get install -y net-tools wget'
      - 'locale-gen en_US.UTF-8'
CONFIG:
  type: aio
  log_level: debug
...
# vim: syntax=yaml
