---
branches:
  except:
  - refactor
  - gh-pages
language: ruby
script: "bundle exec rake spec SPEC_OPTS='--format documentation'"
bundler_args: --without rake
rvm:
  - 1.9.3
  - 2.0.0
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 2.7.0"
    - PUPPET_GEM_VERSION="~> 3.0"
matrix:
  exclude:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.7.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 2.7.0"
notifications:
  email: false  
