---
branches:
  except:
  - refactor
  - gh-pages
sudo: false
language: ruby
cache: bundler
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
bundler_args: --without system_tests
matrix:
  fast_finish: true
  include:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 3.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.0"
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 3.0"
    - rvm: 2.1.0
      env: PUPPET_GEM_VERSION="~> 4.0"
notifications:
  email: false
